name: oraculo_diosa_fortuna
description: Plataforma estadística multiplataforma para Melate Retro.
publish_to: "none"
version: 3.7.0+37

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/historico_retro.csv
    - assets/config/model_config.json
    - assets/images/oraculo_logo.png
    - assets/images/pit_powered_by.png
