name: Build Web

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Generate Web platform
        run: flutter create . --platforms=web --project-name oraculo_diosa_fortuna --org com.primeinnovationthinking

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: Oraculo-Diosa-Fortuna-Web
          path: build/web/
